### PR TITLE
We still need EBI repo

### PR DESCRIPTION
**Pull request by fcyu**
Hi @ypriverol ,

Although most are in the pride-core pom, we still need to add the ECI repo. Otherwise, where do we download the pride-core.pom?

Bests

### CODE REVIEW

**Comment by ypriverol** [comment]
Here you can find the master pom file https://www.ebi.ac.uk/Tools/maven/repos/content/repositories/pst-release/uk/ac/ebi/pride/architectural/pride-core/1.0.1/

**Comment by fcyu** [comment]
Exactly! We also need to tell Maven where to find it. Otherwise, it cannot automatically download it and reports errors in the jmzReader's pom file.

**Comment by ypriverol** [comment]
You need to build before the jmzReader the master parent pom file, then you can build the dependency.

**Comment by mbdebian** [comment]
Hi @fcyu, thanks a lot for your comments.
Unfortunately, our documentation for every PRIDE software artifact may not be completely up to date, so it may not mention that, in order to work with any component of PRIDE software ecosystem you need to include, in your Maven settings, the following Maven repository.
```xml
<repository>
      <id>pst-release</id>
      <name>EBI Nexus Repository</name>
      <url>http://www.ebi.ac.uk/Tools/maven/repos/content/repositories/pst-release</url>
 </repository>
```
That will solve all your dependencies problems.

Thanks,
Manuel

**Comment by noedelta** [comment]
Hi, a small suggestion. I will recommend to use the general EBI for the release dependencies because it was the recommendation when the new nexus set-up was done. It is not team dependent and if the teams change the user it is not affected.

Regards,

Noe

<repository>
    <id>nexus-ebi-release-repo</id>
    <url>http://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-repo/</url>
</repository>
https://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-repo/uk/ac/ebi/pride/architectural/pride-core/1.0.1/ <https://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-repo/uk/ac/ebi/pride/architectural/pride-core/1.0.1/>

Noemi del Toro Ayllón
Software Engineer 
Molecular Interactions Team
European Molecular Biology Laboratory
European Bioinformatics Institute (EMBL-EBI)
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom

**Pull request closed without merging**
